# Generated by Django 3.2.4 on 2021-06-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
